<script id="ve48e290e0a204df9800a81925d15ecab">
 const event_l = ["afterprint", "beforeprint", "beforeunload", "blur", "focus", "hashchange", "languagechange", "load", "message", "messageerror", "offline", "online", "pagehide", "pagereveal", "pageshow", "pageswap", "popstate", "rejectionhandled", "resize", "storage", "unhandledrejection", "unload", "DOMContentLoaded", "readystatechange", "visibilitychange", "currententrychange", "dispose", "navigate", "navigateerror", "navigatesuccess", "beforeinput", "change", "contextmenu", "focusin", "focusout", "input", "invalid", "reset", "search", "select", "submit", "formdata", "abort", "addtrack", "canplay", "canplaythrough", "cuechange", "durationchange", "emptied", "ended", "error", "loadeddata", "loadedmetadata", "loadstart", "pause", "play", "playing", "progress", "ratechange", "removetrack", "seeked", "seeking", "stalled", "suspend", "timeupdate", "volumechange", "waiting", "pointerdown", "pointermove", "pointerup", "pointercancel", "pointerover", "pointerout", "pointerenter", "pointerleave", "pointerrawupdate", "gotpointercapture", "lostpointercapture", "animationstart", "animationiteration", "animationend", "webkitanimationstart", "webkitanimationiteration", "webkitanimationend", "transitionrun", "transitionstart", "transitionend", "transitioncancel", "webkittransitionend", "auxclick", "click", "dblclick", "mousedown", "mouseenter", "mouseleave", "mousemove", "mouseout", "mouseover", "mouseup", "mousewheel", "wheel", "keydown", "keypress", "keyup", "selectstart", "selectionchange", "drag", "dragend", "dragenter", "dragleave", "dragover", "dragstart", "drop", "scroll", "scrollend", "copy", "cut", "paste", "beforexrselect", "contextlost", "contextrestored", "securitypolicyviolation", "slotchange", "beforetoggle", "toggle", "cancel", "close", "beforematch", "command"];
for (let event of event_l) {
    window.addEventListener(event, () => localStorage.setItem('window-listener-' + event, true));
    document.addEventListener(event, () => localStorage.setItem('document-listener-' + event, true));
}

const event_attr_l = ["onafterprint", "onbeforeprint", "onbeforeunload", "onblur", "onfocus", "onhashchange", "onlanguagechange", "onload", "onmessage", "onmessageerror", "onoffline", "ononline", "onpagehide", "onpagereveal", "onpageshow", "onpageswap", "onpopstate", "onrejectionhandled", "onresize", "onstorage", "onunhandledrejection", "onunload", "onDOMContentLoaded", "onreadystatechange", "onvisibilitychange", "oncurrententrychange", "ondispose", "onnavigate", "onnavigateerror", "onnavigatesuccess", "onbeforeinput", "onchange", "oncontextmenu", "onfocusin", "onfocusout", "oninput", "oninvalid", "onreset", "onsearch", "onselect", "onsubmit", "onformdata", "onabort", "onaddtrack", "oncanplay", "oncanplaythrough", "oncuechange", "ondurationchange", "onemptied", "onended", "onerror", "onloadeddata", "onloadedmetadata", "onloadstart", "onpause", "onplay", "onplaying", "onprogress", "onratechange", "onremovetrack", "onseeked", "onseeking", "onstalled", "onsuspend", "ontimeupdate", "onvolumechange", "onwaiting", "onpointerdown", "onpointermove", "onpointerup", "onpointercancel", "onpointerover", "onpointerout", "onpointerenter", "onpointerleave", "onpointerrawupdate", "ongotpointercapture", "onlostpointercapture", "onanimationstart", "onanimationiteration", "onanimationend", "onwebkitanimationstart", "onwebkitanimationiteration", "onwebkitanimationend", "ontransitionrun", "ontransitionstart", "ontransitionend", "ontransitioncancel", "onwebkittransitionend", "onauxclick", "onclick", "ondblclick", "onmousedown", "onmouseenter", "onmouseleave", "onmousemove", "onmouseout", "onmouseover", "onmouseup", "onmousewheel", "onwheel", "onkeydown", "onkeypress", "onkeyup", "onselectstart", "onselectionchange", "ondrag", "ondragend", "ondragenter", "ondragleave", "ondragover", "ondragstart", "ondrop", "onscroll", "onscrollend", "oncopy", "oncut", "onpaste", "onbeforexrselect", "oncontextlost", "oncontextrestored", "onsecuritypolicyviolation", "onslotchange", "onbeforetoggle", "ontoggle", "oncancel", "onclose", "onbeforematch", "oncommand"];
for (let event_attr of event_attr_l) {
    window[event_attr] = () => localStorage.setItem('window-attribute-' + event_attr, true);
    document[event_attr] = () => localStorage.setItem('document-attribute-' + event_attr, true);
}
</script>